### ISSUE TITLE
missing libs etc

### ISSUE THREAD

**Issue by sebastienjouhans** [fx-lange/ofxGSTT#1]
Hi,

I am trying to recompile the library but unsuccessfully. As mentioned in the readme file, the project relies on some other libraries...
Would you be able to provide a package which includes all the libs in the project?

Thanks
S

**Comment by fx-lange** [comment]
Yes I wanted to add the libs this week anyway. On which OS are you working on?

**Comment by sebastienjouhans** [comment]
osx

**Comment by fx-lange** [comment]
I'm still working on it but have problems building the static libs for mac. details can be found [here](http://forum.openframeworks.cc/index.php/topic,8293.0.html)

**Comment by dackdel** [comment]
did you add the libraries? also what did you do about the flac and 64bit? I saw your post but did you get any further?

**Comment by fx-lange** [comment]
no, not yet and I don't have a mac at home anymore but I want to solve this after finishing my bachelor thesis this month.  my next step will be to exclude libFlac at all because sndfile can write flac files itself.

**Comment by fx-lange** [comment]
finally got rid of the flac dependency.
