### ISSUE TITLE
unknown type name "ofSoundBuffer"

### ISSUE THREAD

**Issue by nosarious** [fx-lange/ofxGSTT#3]
I don't seem to have ofSoundBuffer on my open frameworks (of_0.8.4) 

are you using a new system, or is mine just corrupted some way?

I am referencing this question, and tried some of their solutions, but something seems wonky.

http://forum.openframeworks.cc/t/help-trying-to-run-master-branch/18318/5

I should add that this version of open frameworks is from September. was ofsoundbuffer added after that?

**Comment by fx-lange** [comment]
hey @nosarious,

yes, ofSoundBuffer doesn't exist in of084. it is a new class. ofxGSTT should run with the current master (of090). I could have a look into ofxGSTT again and see if I can port it back to of084.  I could probably look into this in the next couple of days. are you trying the chrome workaround or the normal example? and which platform btw?

if it is urgent you could try to get it running with of090.

**Comment by fx-lange** [comment]
and @nosarious the class was added Nov 22, 2014

**Comment by nosarious** [comment]
Thank you, Felix.

I am trying this under windows (third installation of windows) and may be
downloading of090 over the next while. This is on a windows 8 partition in
parallels on a mac, eventually a macbook pro.

I tried the latest nightly for mac OS X and noticed it didn't have any of
the Xcode stuff necessary to running files. I hope the visual
studio/windows version does.

I am currently testing builds of empty examples, trying to track down and
fix errors in open frameworks prior to re-installing kinectcommonbridge. I
had a lot of trouble using the original "add everything in and start"
attempt, when I got a number of error codes which were very frustrating.

Thanks for the update on the date it was added. I loves open frameworks and
cannot wait for the next (stable) version to come out. I couldn't have
completed my thesis without it.

**Comment by fx-lange** [comment]
hey @nosarious, 

sounds like a complicated setup. so 084 is not an option anyway because of the kinect dependencies or would a 084 versioin of ofxGSTT help?

good luck with the win install!

**Comment by nosarious** [comment]
on my third try with open frameworks on this new windows partition.
thankfully I duplicated the image before starting.

I tried github to clone the latest version of open frameworks, but the lack
of feedback while it is cloning (a spinning cursor, but no indication of
how much as been cloned) made me quit it in frustration.

I'm copying the version I got from a mac version of git cloning. (which was
done in two minutes). Finding the visual studio files seems kind of
daunting. I guess that's the 'bleeding' part of 'bleeding edge'

If you have a 0.8.4 version kicking around, that would be great. Did you
ever have the audio working on it? I really want to have the audio/words
heard by a kinect to use in this piece... Hopefully with more than one
Kinect. I found hints of an apple dictation frameworks, but no one has made
anything to use it in open frameworks (and it is probably only an iosKit
framework)

Any help you might be able to give me would be appreciated. I've tried so
many speech thingies, and all seem to have problems with no solutions.

Gerry.

**Comment by nosarious** [comment]
... forgive me for all of my complaining.

I just discovered the nightly build for open frameworks is actually
intended for visceral studio 2015.

I 'may' have everything set up now to start testing later tonight or
tomorrow.

... this is the fifth day of a single experiment to see if I can 'listen'
to regular conversations and use the text graphically in an art piece.

I can only hope it works. I'll let you know if I can get things working.

Thanks for getting back to me and my whining frustration.

Gerry

http://www.gersart.ca

**Comment by nosarious** [comment]
zOMG. I completely got your stuff mixed up with stuff that I was getting
tied down with.

er... sorry?

I was trying so many things over the weekend that I screwed them up. Your
suggestions for using the nightly build (which requires VS2015) 'did' help
me get ofxkinectcommonbridge up and running, though. so... uh, thanks?

I will be trying ofxgstt later this afternoon.

Thanks for your help...

Gerry.

**Comment by fx-lange** [comment]
could you get in running? the 0.8.4 version shouldn't be needed anymore now that RC1 of 0.9 is out. have you tried it?

**Comment by nosarious** [comment]
Hi there. 

I tried the premise of how this worked in a similar processing sketch, and a localhost based website on a mac set up in apache. The timing for what one gets, and the behaviour of the text that was generated would have been a similar setup to yours.It was ultimately the limitation of only having a single microphone source available per machine, as defined by how the google speech API works, which implied these solutions-through-chrome would not work for my needs ...

Thank you very much for getting back to me. Your system 'almost' worked, but there was a glitch in some part of how I ended up implementing the code which made it not work. The test-with-processing demonstrated your solution may not have been the best course for me at that point.

I am currently trying to figure out how to recode the legacy code introduced in this forum thread: http://forum.openframeworks.cc/t/voice-recognition-libs-sphinx/488/66

I found th old code, but it was made in 2008, and many of the add ons mentioned have become part of the core of openframeworks, so I have to adjust and rework it before I can test it properly.

**Comment by fx-lange** [comment]
Yes an multi microphone setup might be complicated with the chrome workaround. Sadly the limit to 50-500 requests a day makes the addon kind of useless for art installations and similar applications. Still it has it purpose for prototyping. 

Good luck with your project. Will close the issue, now that of 0.9 rc1 it out (with ofSoundBuffer).

**Comment by nosarious** [comment]
Thank you very  much for your help on this. I really did appreciate it.
